### PR TITLE
Add toastr_clear_all function

### PR DESCRIPTION
**Pull request by Tutuchan**
Hi and thanks for this port of **toastr** !

This PR introduces a small function to clear/remove all existing toasts.

Example: 

``` r

library(shinytoastr)

ui <- shinyUI(fluidPage(
  useToastr(),
  pageWithSidebar(
    headerPanel("Header"),
    sidebarPanel(
      actionButton(inputId = "save_button", label = "Save",
                   class = "btn-primary"),
      actionButton(inputId = "clear_button", label = "Clear",
                   class = "btn-danger")
    ),
    mainPanel(
    )
  )
))

server <- function(input, output, session) {

  observeEvent(
    input$save_button,
    {
      tryCatch(
        {
          writeToDB(data)
          toastr_success("Saved to database")
        },
        error = function(e) {
          toastr_error(title = "Database error", conditionMessage(e))
        }
      )
    }
  )
  observeEvent(
    input$clear_button,
    {
      clear_toasts(with_animation = TRUE)
    }
  )
}

shinyApp(ui = ui, server = server)
```

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! 

Hmmm. What's wrong with just clicking on the notification? Doesn't that remove it? Although if you make the message permanent, then maybe it does not....

**Comment by Tutuchan** [comment]
It's true, you can just click on the notification, even it is permanent. The idea here is to be able to remove a notification when another event occurs, for example when a computation is finished. 

Here is a basic version of the functionality I wanted to have:

``` r
library(shiny)
library(shinytoastr)

ui <- fluidPage(
  useToastr(),
  actionButton("ab", label = "Go")
)

server <- shinyServer(function(input, output, session) {

  observeEvent(input$ab, {
    toastr_info("Initializing ...", timeOut = 0)
    Sys.sleep(2)
    clear_toasts()
    toastr_success("Initialized !")
  })
})

runApp(list(ui = ui, server = server))
```

**Comment by gaborcsardi** [comment]
OK, got it. Another thing. How about calling it `toastr_clear_all()`, so that all functions have the same prefix?

**Comment by Tutuchan** [comment]
That makes sense, let me change that.

**Comment by gaborcsardi** [comment]
Great, thanks!

**Pull request merged**
